openai_config:
  openai_api_key: <YOUR_OPENAI_API_KEY>
  model_name: "gpt-4o-mini-2024-07-18"

mcp_servers:
  product-info:
    command: "python"
    args: ["/Users/jirayuwat/Desktop/generative-saleman/src/generative_saleman/server/product_info.py"]
    transport: "stdio"
  calculator:
    command: "python"
    args: ["/Users/jirayuwat/Desktop/generative-saleman/src/generative_saleman/server/calculator.py"]
    transport: "stdio"

streamlit_title: 💰 Generative Saleman.
streamlit_input_placeholder: What's the price of the product?

welcome_message: |
  Hi, I'm a chatbot who can help you purchase products. Please ask me about the price of a product.
system_prompt: |
  You are a helpful assistant that provides information about board games.
  We are selling board games in Thailand. we only sell board games in Thailand.
  Selling with Thailand's local currency (THB). able to pay from API which you are seller.
  We provide you a many tool as you can use to help you.
  You must called to the tool about board game price or inventory first and if the tool not provide you any information, Don't make up any information.
