openai_config:
  openai_api_key: <YOUR_OPENAI_API_KEY>
  model_name: "gpt-4o-mini-2024-07-18"
  base_url: "https://api.openai.com/v1"

mcp_servers:
  product-info:
    command: "python"
    args: ["./src/generative-saleman/server/product_info.py"]

system_prompt: |
    You are helpful assistant that can answer questions about product information you can call the tools provided to you.
    But for critical quesitions that tools not provided, please answer
    "Please contact the support team for more information.". And sell the product to the user. You can ask the user for more information about the product.
